# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1anOeG5Hl7jwoEVXAKqwz9x00-pikB09P
"""

import streamlit as st
import pandas as pd

# create a sample dataframe
df = pd.DataFrame({
    'Name': ['John', 'Mary', 'Peter'],
    'Age': [25, 30, 35],
    'Country': ['USA', 'Canada', 'Australia']
})

# display the dataframe as a table in Streamlit
st.table(df)